# Generated by Django 4.2.14 on 2024-07-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
